// JobTrack built-in company suggestion database.
// Edit this file whenever you want to add or remove companies.
// script.js combines these names with companies from your saved applications.

window.JOBTRACK_COMPANY_CATEGORIES = {
    'Technology & Software': [
        "Accenture",
        "Adobe",
        "Akamai Technologies",
        "Alibaba",
        "Alphabet",
        "Amazon",
        "AMD",
        "Amphenol",
        "Analog Devices",
        "Ansys",
        "Apple",
        "Applied Materials",
        "Arm",
        "Asana",
        "Atlassian",
        "Autodesk",
        "Automatic Data Processing",
        "Broadcom",
        "Cadence Design Systems",
        "Canon",
        "Capgemini",
        "CDW",
        "Cisco",
        "Cloudflare",
        "Cognizant",
        "CommScope",
        "Confluent",
        "CrowdStrike",
        "Datadog",
        "Dell Technologies",
        "DigitalOcean",
        "DocuSign",
        "Dropbox",
        "DXC Technology",
        "Elastic",
        "Electronic Arts",
        "EPAM Systems",
        "Ericsson",
        "F5",
        "Fastly",
        "Fortinet",
        "Garmin",
        "Gen Digital",
        "GitHub",
        "GitLab",
        "GoDaddy",
        "Google",
        "Hewlett Packard Enterprise",
        "HP",
        "HubSpot",
        "IBM",
        "Indeed",
        "Informatica",
        "Infosys",
        "Intel",
        "Intuit",
        "Juniper Networks",
        "Kyndryl",
        "Lenovo",
        "Logitech",
        "Marvell Technology",
        "Meta",
        "Micron Technology",
        "Microsoft",
        "MongoDB",
        "Motorola Solutions",
        "NCR Voyix",
        "NetApp",
        "Nokia",
        "Nutanix",
        "NVIDIA",
        "Okta",
        "OpenAI",
        "Oracle",
        "Palantir",
        "Palo Alto Networks",
        "Paycom",
        "Paylocity",
        "Pegasystems",
        "Qualcomm",
        "Red Hat",
        "Roku",
        "Salesforce",
        "SAP",
        "ServiceNow",
        "Shopify",
        "Siemens Digital Industries Software",
        "Slack",
        "Snowflake",
        "Sony Interactive Entertainment",
        "Splunk",
        "Spotify",
        "Synopsys",
        "Tata Consultancy Services",
        "TE Connectivity",
        "Texas Instruments",
        "Twilio",
        "UiPath",
        "VMware",
        "Western Digital",
        "Workday",
        "X",
        "Xerox",
        "Yelp",
        "Zoom",
        "Zscaler",
    ],
    'Finance & Insurance': [
        "Aflac",
        "Allstate",
        "American Express",
        "Ameriprise Financial",
        "Aon",
        "Apollo Global Management",
        "Bank of America",
        "Bank of New York Mellon",
        "Barclays",
        "Berkshire Hathaway",
        "BlackRock",
        "Blackstone",
        "Capital One",
        "Charles Schwab",
        "Chime",
        "Cigna",
        "Citigroup",
        "Citizens Financial Group",
        "CME Group",
        "Coinbase",
        "Discover Financial Services",
        "Edward Jones",
        "Fidelity Investments",
        "Fifth Third Bank",
        "Fiserv",
        "Goldman Sachs",
        "Guardian Life",
        "Hartford Financial Services",
        "HSBC",
        "Huntington Bancshares",
        "Intercontinental Exchange",
        "JPMorgan Chase",
        "KeyBank",
        "KKR",
        "Liberty Mutual",
        "Lincoln Financial Group",
        "Marsh McLennan",
        "Mastercard",
        "MetLife",
        "Morgan Stanley",
        "Nationwide",
        "Nasdaq",
        "Navient",
        "New York Life",
        "Northern Trust",
        "PayPal",
        "PNC Financial Services",
        "Prudential Financial",
        "Raymond James",
        "Robinhood",
        "SoFi",
        "State Farm",
        "Synchrony",
        "TD Bank",
        "The Travelers Companies",
        "Truist",
        "U.S. Bancorp",
        "USAA",
        "Visa",
        "Wells Fargo",
        "Western Union",
        "Zurich Insurance Group",
    ],
    'Defense, Aerospace & Government Contractors': [
        "AAR Corp",
        "AeroVironment",
        "BAE Systems",
        "Boeing",
        "Booz Allen Hamilton",
        "CACI International",
        "CAE",
        "Curtiss-Wright",
        "General Dynamics",
        "HII",
        "Honeywell Aerospace",
        "Jacobs",
        "KBR",
        "Kratos Defense & Security Solutions",
        "L3Harris Technologies",
        "Leidos",
        "Leonardo DRS",
        "Lockheed Martin",
        "ManTech",
        "Maxar Technologies",
        "Northrop Grumman",
        "Parsons",
        "Peraton",
        "RTX",
        "SAIC",
        "Sierra Nevada Corporation",
        "SpaceX",
        "Textron",
        "V2X",
        "Viasat",
    ],
    'Consulting & Professional Services': [
        "Alvarez & Marsal",
        "Bain & Company",
        "BCG",
        "BDO USA",
        "Booz Allen Hamilton",
        "Capgemini",
        "CGI",
        "Deloitte",
        "EY",
        "FTI Consulting",
        "Grant Thornton",
        "Guidehouse",
        "HCLTech",
        "Infosys",
        "KPMG",
        "McKinsey & Company",
        "NTT DATA",
        "Perficient",
        "Protiviti",
        "PwC",
        "Slalom",
        "Tata Consultancy Services",
        "Thoughtworks",
        "Wipro",
    ],
    'Healthcare & Life Sciences': [
        "Abbott",
        "AbbVie",
        "Aetna",
        "Agilent Technologies",
        "Amgen",
        "Baxter International",
        "Becton Dickinson",
        "Biogen",
        "Boston Scientific",
        "Bristol Myers Squibb",
        "Cardinal Health",
        "Centene",
        "Cigna",
        "CVS Health",
        "Danaher",
        "DaVita",
        "Eli Lilly",
        "Elevance Health",
        "GE HealthCare",
        "Gilead Sciences",
        "HCA Healthcare",
        "Humana",
        "IQVIA",
        "Johnson & Johnson",
        "Kaiser Permanente",
        "Labcorp",
        "McKesson",
        "Medtronic",
        "Merck",
        "Moderna",
        "Molina Healthcare",
        "Novo Nordisk",
        "Pfizer",
        "Quest Diagnostics",
        "Regeneron",
        "Roche",
        "Sanofi",
        "Stryker",
        "Thermo Fisher Scientific",
        "UnitedHealth Group",
        "Vertex Pharmaceuticals",
        "Walgreens Boots Alliance",
        "Zimmer Biomet",
    ],
    'Retail & E Commerce': [
        "Abercrombie & Fitch",
        "Academy Sports + Outdoors",
        "Albertsons",
        "Aldi",
        "Amazon",
        "AutoZone",
        "Bath & Body Works",
        "Best Buy",
        "BJ's Wholesale Club",
        "Burlington Stores",
        "CarMax",
        "Chewy",
        "Costco",
        "CVS Health",
        "Dick's Sporting Goods",
        "Dollar General",
        "Dollar Tree",
        "eBay",
        "Etsy",
        "Foot Locker",
        "Gap",
        "Home Depot",
        "IKEA",
        "Kohl's",
        "Kroger",
        "Lowe's",
        "Macy's",
        "Meijer",
        "Nordstrom",
        "Office Depot",
        "Petco",
        "PetSmart",
        "Publix",
        "REI",
        "Ross Stores",
        "Sam's Club",
        "Sephora",
        "Shopify",
        "Staples",
        "Target",
        "TJX Companies",
        "Tractor Supply",
        "Ulta Beauty",
        "Walgreens",
        "Walmart",
        "Wayfair",
        "Whole Foods Market",
        "Williams-Sonoma",
    ],
    'Media, Entertainment & Gaming': [
        "Activision Blizzard",
        "AMC Networks",
        "Audacy",
        "Comcast",
        "Condé Nast",
        "Discord",
        "Electronic Arts",
        "Epic Games",
        "Fox Corporation",
        "GameStop",
        "iHeartMedia",
        "Lionsgate",
        "Live Nation Entertainment",
        "Netflix",
        "Nintendo",
        "Paramount Global",
        "Riot Games",
        "Roblox",
        "SiriusXM",
        "Sony",
        "Spotify",
        "Take-Two Interactive",
        "The New York Times",
        "The Walt Disney Company",
        "Twitch",
        "Universal Music Group",
        "Warner Bros. Discovery",
        "Warner Music Group",
        "YouTube",
        "Zynga",
    ],
    'Telecom & Connectivity': [
        "AT&T",
        "Brightspeed",
        "Charter Communications",
        "Comcast",
        "Cox Communications",
        "Crown Castle",
        "Ericsson",
        "Frontier Communications",
        "Lumen Technologies",
        "Nokia",
        "Qualcomm",
        "T-Mobile",
        "Verizon",
        "Viasat",
        "Windstream",
    ],
    'Transportation, Logistics & Airlines': [
        "Alaska Airlines",
        "American Airlines",
        "Amtrak",
        "Avis Budget Group",
        "C.H. Robinson",
        "CSX",
        "Delta Air Lines",
        "Expeditors International",
        "FedEx",
        "Flexport",
        "Hertz",
        "JB Hunt Transport Services",
        "JetBlue",
        "Knight-Swift Transportation",
        "Lyft",
        "Norfolk Southern",
        "Old Dominion Freight Line",
        "Ryder System",
        "Southwest Airlines",
        "Spirit Airlines",
        "Uber",
        "Union Pacific",
        "United Airlines",
        "UPS",
        "XPO",
    ],
    'Automotive & Mobility': [
        "AutoNation",
        "BMW Group",
        "CarGurus",
        "CarMax",
        "Carvana",
        "Caterpillar",
        "Cummins",
        "Ford",
        "General Motors",
        "Goodyear",
        "Honda",
        "Hyundai Motor Group",
        "Kia",
        "Lucid Motors",
        "Mercedes-Benz",
        "Nissan",
        "PACCAR",
        "Rivian",
        "Stellantis",
        "Tesla",
        "Toyota",
        "Volkswagen Group",
        "Volvo Group",
    ],
    'Industrial, Energy & Utilities': [
        "3M",
        "AES",
        "Air Products",
        "American Electric Power",
        "Baker Hughes",
        "Chevron",
        "ConocoPhillips",
        "Constellation Energy",
        "Cummins",
        "Dominion Energy",
        "Duke Energy",
        "Eaton",
        "Emerson",
        "Enphase Energy",
        "EOG Resources",
        "Exelon",
        "ExxonMobil",
        "FirstEnergy",
        "Freeport-McMoRan",
        "GE Vernova",
        "Halliburton",
        "Honeywell",
        "Johnson Controls",
        "Kinder Morgan",
        "Marathon Petroleum",
        "National Grid",
        "NextEra Energy",
        "NRG Energy",
        "Occidental Petroleum",
        "ONEOK",
        "Phillips 66",
        "PPL Corporation",
        "Schneider Electric",
        "Shell",
        "Siemens",
        "Southern Company",
        "Suncor Energy",
        "Tesla Energy",
        "Valero Energy",
        "Vistra",
        "Williams Companies",
        "Xcel Energy",
    ],
    'Manufacturing & Consumer Goods': [
        "Archer Daniels Midland",
        "Ball Corporation",
        "BASF",
        "Cargill",
        "Clorox",
        "Colgate-Palmolive",
        "Conagra Brands",
        "Corning",
        "Dow",
        "DuPont",
        "Eastman Chemical",
        "General Mills",
        "Georgia-Pacific",
        "Hershey",
        "Hormel Foods",
        "International Paper",
        "Jabil",
        "Kellanova",
        "Kimberly-Clark",
        "Kraft Heinz",
        "L'Oréal",
        "Mars",
        "Mondelez International",
        "Newell Brands",
        "Nike",
        "PepsiCo",
        "Procter & Gamble",
        "Stanley Black & Decker",
        "Tyson Foods",
        "Unilever",
        "Whirlpool",
    ],
    'Food, Beverage & Hospitality': [
        "Aramark",
        "Bloomin' Brands",
        "Chipotle Mexican Grill",
        "Coca-Cola",
        "Darden Restaurants",
        "Domino's",
        "DoorDash",
        "Hilton",
        "Hyatt",
        "Keurig Dr Pepper",
        "Marriott International",
        "McDonald's",
        "PepsiCo",
        "Restaurant Brands International",
        "Starbucks",
        "Sysco",
        "The Cheesecake Factory",
        "The Wendy's Company",
        "Uber Eats",
        "Yum! Brands",
    ],
    'Real Estate & Construction': [
        "AECOM",
        "Bechtel",
        "CBRE",
        "Colliers",
        "D.R. Horton",
        "Fluor",
        "Jacobs",
        "JLL",
        "Kiewit",
        "Lennar",
        "MasTec",
        "PulteGroup",
        "Skanska",
        "Turner Construction",
        "Vulcan Materials",
        "WSP",
        "Zillow",
    ],
    'Education & Learning': [
        "2U",
        "Arizona State University",
        "Chegg",
        "Coursera",
        "DeVry University",
        "Duolingo",
        "Georgia State University",
        "Grand Canyon University",
        "Khan Academy",
        "Pearson",
        "Southern New Hampshire University",
        "Stride",
        "Udemy",
        "University of Phoenix",
        "Western Governors University",
    ],
    'Cybersecurity': [
        "Akamai Technologies",
        "Arctic Wolf",
        "Check Point Software",
        "Cloudflare",
        "CrowdStrike",
        "CyberArk",
        "Darktrace",
        "DigiCert",
        "Dragos",
        "Fortinet",
        "Gen Digital",
        "HackerOne",
        "KnowBe4",
        "Mandiant",
        "Mimecast",
        "Netskope",
        "Okta",
        "Palo Alto Networks",
        "Proofpoint",
        "Rapid7",
        "Recorded Future",
        "Rubrik",
        "SailPoint",
        "SentinelOne",
        "Sophos",
        "Tenable",
        "Trellix",
        "Varonis",
        "Zscaler",
    ],
    'Georgia & Southeast Employers': [
        "AGCO",
        "Assurant",
        "Autotrader",
        "Carter's",
        "Chick-fil-A",
        "Coca-Cola",
        "Cox Automotive",
        "Cox Communications",
        "Delta Air Lines",
        "Equifax",
        "Georgia Power",
        "Global Payments",
        "Genuine Parts Company",
        "Georgia-Pacific",
        "Home Depot",
        "Inspire Brands",
        "Intercontinental Exchange",
        "Mailchimp",
        "Mohawk Industries",
        "NCR Voyix",
        "Norfolk Southern",
        "Piedmont Healthcare",
        "RaceTrac",
        "Southern Company",
        "Synovus",
        "Truist",
        "UPS",
        "WestRock",
    ],
    'Startups & High Growth Tech': [
        "Airtable",
        "Anthropic",
        "Brex",
        "Canva",
        "Carta",
        "Celonis",
        "Databricks",
        "Deel",
        "Figma",
        "Gong",
        "Grammarly",
        "HashiCorp",
        "Intercom",
        "Klaviyo",
        "Miro",
        "Notion",
        "OpenAI",
        "Plaid",
        "Ramp",
        "Rippling",
        "Samsara",
        "Scale AI",
        "Sentry",
        "Stripe",
        "Vercel",
        "Webflow",
        "Zapier",
    ],
    'Public Sector & Nonprofit': [
        "Centers for Disease Control and Prevention",
        "City of Atlanta",
        "Federal Bureau of Investigation",
        "Federal Reserve",
        "Georgia Department of Transportation",
        "Internal Revenue Service",
        "National Aeronautics and Space Administration",
        "National Security Agency",
        "Smithsonian Institution",
        "United States Air Force",
        "United States Army",
        "United States Department of Defense",
        "United States Department of Homeland Security",
        "United States Department of Veterans Affairs",
        "United States Marine Corps",
        "United States Navy",
        "United States Postal Service",
    ],
    'More Major Employers': [
        "ADP",
        "Advance Auto Parts",
        "Alcoa",
        "Ally Financial",
        "American Tower",
        "Ameren",
        "Amtrak",
        "Avery Dennison",
        "Baker Tilly",
        "BorgWarner",
        "Boston Consulting Group",
        "Brown & Brown",
        "Builders FirstSource",
        "Camping World",
        "Carpenter Technology",
        "Celanese",
        "Centene",
        "Ceridian",
        "CHS",
        "Church & Dwight",
        "Cintas",
        "Cleveland-Cliffs",
        "Cognex",
        "CoStar Group",
        "Cummins",
        "Dentsply Sirona",
        "Dover",
        "Ecolab",
        "Edison International",
        "Eversource Energy",
        "Expedia Group",
        "Fastenal",
        "Ferguson",
        "Fiserv",
        "Fortive",
        "Gartner",
        "Grainger",
        "H&R Block",
        "Henry Schein",
        "Hess",
        "Hologic",
        "Huntsman",
        "IDEXX Laboratories",
        "Illumina",
        "Ingersoll Rand",
        "IQVIA",
        "Iron Mountain",
        "J.M. Smucker",
        "KLA",
        "Lamb Weston",
        "Lowe's",
        "Lululemon",
        "ManpowerGroup",
        "MarketAxess",
        "Martin Marietta Materials",
        "Masco",
        "Match Group",
        "McCormick & Company",
        "MGM Resorts International",
        "Mohawk Industries",
        "Molson Coors",
        "Nasdaq",
        "NetApp",
        "Newmont",
        "News Corp",
        "Nucor",
        "Otis Worldwide",
        "PACCAR",
        "Parker Hannifin",
        "Paychex",
        "Pinterest",
        "PPG Industries",
        "Principal Financial Group",
        "Quanta Services",
        "Quest Diagnostics",
        "Republic Services",
        "ResMed",
        "Rockwell Automation",
        "Roper Technologies",
        "Royal Caribbean Group",
        "S&P Global",
        "Sherwin-Williams",
        "Snap",
        "Snap-on",
        "State Street",
        "Steel Dynamics",
        "Synchrony",
        "T. Rowe Price",
        "TE Connectivity",
        "Teradyne",
        "Trane Technologies",
        "TransUnion",
        "United Rentals",
        "Verisk",
        "Vulcan Materials",
        "Waste Management",
        "Weyerhaeuser",
        "WW Grainger",
        "Yum China",
        "Zoetis",
    ],
    'Additional Employers': [
        "Abbott Laboratories",
        "Abercrombie & Fitch Co.",
        "ABM Industries",
        "Acadia Healthcare",
        "Adobe Systems",
        "ADT",
        "Akamai",
        "Albertsons Companies",
        "Allegiant Travel",
        "AllianceBernstein",
        "Alliant Energy",
        "Allison Transmission",
        "Alnylam Pharmaceuticals",
        "Americold Realty Trust",
        "Ametek",
        "Amkor Technology",
        "AppFolio",
        "Arthur J. Gallagher",
        "Ashland",
        "Aspen Technology",
        "Axon Enterprise",
        "Bath & Body Works",
        "Bausch + Lomb",
        "Bentley Systems",
        "Bio-Rad Laboratories",
        "Bio-Techne",
        "Blackbaud",
        "Blue Cross Blue Shield",
        "Box",
        "Broadridge Financial Solutions",
        "Brown-Forman",
        "Bunge",
        "Cadence Bank",
        "Caesars Entertainment",
        "Campbell Soup Company",
        "Caris Life Sciences",
        "Catalent",
        "Cboe Global Markets",
        "Cerence",
        "Charles River Laboratories",
        "Chipotle",
        "Ciena",
        "Citrix",
        "Clearwater Analytics",
        "Cloudera",
        "Coca-Cola Consolidated",
        "Cognex",
        "Coinbase Global",
        "Commvault",
        "CoreLogic",
        "Corpay",
        "Crown Equipment",
        "Dataminr",
        "Deckers Brands",
        "Docusign",
        "Dolby Laboratories",
        "DraftKings",
        "Dropbox Inc.",
        "Dynatrace",
        "Ecolab Inc.",
        "Encompass Health",
        "Entrust",
        "Esri",
        "Etsy Inc.",
        "EverCommerce",
        "Exact Sciences",
        "Experian",
        "FactSet",
        "FanDuel",
        "Fidelity National Financial",
        "Five Below",
        "Flex",
        "Fortrea",
        "Freshworks",
        "Genpact",
        "GlobalFoundries",
        "GoTo",
        "Grubhub",
        "Guidewire Software",
        "H&R Block",
        "HCA",
        "Henry Schein",
        "Highmark Health",
        "Hootsuite",
        "Hyland Software",
        "ICF",
        "Indeed.com",
        "Insperity",
        "Instacart",
        "Intuitive Surgical",
        "Jabil Inc.",
        "JBT Marel",
        "JetBrains",
        "Kaseya",
        "Keysight Technologies",
        "Kohl's Corporation",
        "Korn Ferry",
        "Lattice Semiconductor",
        "LendingTree",
        "LexisNexis",
        "LiveRamp",
        "Marqeta",
        "MathWorks",
        "McAfee",
        "Microchip Technology",
        "MicroStrategy",
        "Morningstar",
        "MSCI",
        "Nasdaq Inc.",
        "National Instruments",
        "Netscout",
        "New Relic",
        "Nextdoor",
        "NortonLifeLock",
        "Nuance Communications",
        "O'Reilly Auto Parts",
        "OneTrust",
        "OpenText",
        "PagerDuty",
        "Paycor",
        "Payoneer",
        "PayPal Holdings",
        "Peloton",
        "Pinterest Inc.",
        "Progress Software",
        "Pure Storage",
        "Q2 Holdings",
        "Rackspace Technology",
        "Redfin",
        "RingCentral",
        "Robert Half",
        "Sage",
        "Samsara Inc.",
        "Schneider National",
        "Seagate Technology",
        "Semtech",
        "SiFive",
        "Smartsheet",
        "SolarWinds",
        "SonicWall",
        "Splunk Inc.",
        "Squarespace",
        "Sumo Logic",
        "Toast",
        "TransPerfect",
        "Trimble",
        "Twilio Inc.",
        "Unity Software",
        "Upwork",
        "Verint Systems",
        "Verisign",
        "Vimeo",
        "Wayfair Inc.",
        "Wix",
        "Wolters Kluwer",
        "ZoomInfo",
        "Zywave",
    ],
    'Additional National Employers': [
        "AAA",
        "AARP",
        "AB InBev",
        "ADP",
        "AECOM",
        "AIG",
        "Airtel",
        "Akamai",
        "Albertsons",
        "Alexandria Real Estate Equities",
        "Allied Universal",
        "Alorica",
        "Amcor",
        "AmerisourceBergen",
        "Angi",
        "Apex Systems",
        "ARAMARK",
        "Arista Networks",
        "Arrow Electronics",
        "Ascension",
        "Auto-Owners Insurance",
        "Avangrid",
        "Avnet",
        "Baker McKenzie",
        "Bally's Corporation",
        "Banner Health",
        "Bath & Body Works Inc.",
        "Baylor Scott & White Health",
        "BDO",
        "Blue Origin",
        "Blue Yonder",
        "Booking Holdings",
        "Bosch",
        "Brinks",
        "Brookfield Properties",
        "Brown Brothers Harriman",
        "Burlington",
        "C.H. Robinson Worldwide",
        "Canon USA",
        "Capgemini America",
        "Carvana Co.",
        "CDK Global",
        "CDW Corporation",
        "Cerner",
        "Chase",
        "Children's Healthcare of Atlanta",
        "Cleveland Clinic",
        "Cox Enterprises",
        "Crowe",
        "CVS Pharmacy",
        "Dana Incorporated",
        "DHL",
        "DISH Network",
        "DocuSign Inc.",
        "DoorDash Inc.",
        "DraftKings Inc.",
        "Emory Healthcare",
        "Emory University",
        "Enterprise Mobility",
        "Ernst & Young",
        "Eversana",
        "Expedia",
        "Experis",
        "EY-Parthenon",
        "Farmers Insurance",
        "Federal Express",
        "Ferguson Enterprises",
        "Fiserv Inc.",
        "Florida Blue",
        "GE Aerospace",
        "GEICO",
        "Georgia Tech",
        "Giant Eagle",
        "Grainger",
        "Grant Thornton LLP",
        "Graybar",
        "HCA Florida Healthcare",
        "HCL America",
        "Hearst",
        "Hitachi",
        "Humana Inc.",
        "Hyundai Motor America",
        "Infor",
        "Insight Enterprises",
        "Instacart Inc.",
        "Intercontinental Hotels Group",
        "JLL Technologies",
        "John Deere",
        "Johns Hopkins Medicine",
        "Kaiser",
        "Koch Industries",
        "KPMG LLP",
        "Labcorp Holdings",
        "LendingClub",
        "Lowe's Companies",
        "Mayo Clinic",
        "Memorial Sloan Kettering",
        "Mercedes-Benz USA",
        "Mercer",
        "Molina",
        "Nasdaq Stock Market",
        "Navy Federal Credit Union",
        "NBCUniversal",
        "NCR Atleos",
        "New York-Presbyterian",
        "Nielsen",
        "Nissan North America",
        "NTT Data Services",
        "Oracle America",
        "Penske",
        "Piedmont",
        "Piper Sandler",
        "Progressive Insurance",
        "Publicis Sapient",
        "Rackspace",
        "Raytheon Technologies",
        "Regions Bank",
        "Robert Half International",
        "Rocket Companies",
        "Samsung",
        "Schneider Electric USA",
        "Securitas",
        "Siemens USA",
        "Sirius Computer Solutions",
        "Sodexo",
        "SouthState Bank",
        "Spectrum",
        "State Street Corporation",
        "SunTrust",
        "Synovus Financial",
        "TIAA",
        "TTEC",
        "Turner Broadcasting",
        "UCB",
        "United Parcel Service",
        "UnitedHealth",
        "University of Georgia",
        "US Foods",
        "Vanguard",
        "WarnerMedia",
        "Wells Fargo Bank",
        "West Monroe",
        "Westinghouse Electric Company",
        "World Wide Technology",
        "Yahoo",
        "Yardi Systems",
        "Yum Brands",
    ],
};

// Flatten every category into one alphabetized, duplicate-free array for autocomplete.
window.JOBTRACK_COMPANIES = [...new Set(
    Object.values(window.JOBTRACK_COMPANY_CATEGORIES).flat()
)].sort((a, b) => a.localeCompare(b));

// Built-in unique company suggestions: 974