// JobTrack built-in job title database.
// Users are NOT limited to these titles. Any custom title can still be typed and saved.
// Saved custom titles are automatically learned by script.js and suggested later.

window.JOBTRACK_JOB_TITLES = [
    "3D Artist",
    "Academic Advisor",
    "Accessibility Specialist",
    "Account Executive",
    "Account Manager",
    "Accountant",
    "Accounts Payable Specialist",
    "Accounts Receivable Specialist",
    "Active Directory Administrator",
    "Administrative Assistant",
    "Admissions Counselor",
    "Aerospace Engineer",
    "AI Engineer",
    "Aircraft Mechanic",
    "All Source Intelligence Analyst",
    "Analytics Engineer",
    "Android Developer",
    "Animator",
    "Application Developer",
    "Application Security Engineer",
    "Assistant Manager",
    "Assistant Store Manager",
    "Associate Back End Developer",
    "Associate Business Analyst",
    "Associate Civil Engineer",
    "Associate Cloud Engineer",
    "Associate Cybersecurity Analyst",
    "Associate Data Analyst",
    "Associate Data Engineer",
    "Associate Data Scientist",
    "Associate DevOps Engineer",
    "Associate Electrical Engineer",
    "Associate Financial Analyst",
    "Associate Front End Developer",
    "Associate Full Stack Developer",
    "Associate Help Desk Technician",
    "Associate Industrial Engineer",
    "Associate IT Support Specialist",
    "Associate Machine Learning Engineer",
    "Associate Management Analyst",
    "Associate Marketing Analyst",
    "Associate Mechanical Engineer",
    "Associate Network Engineer",
    "Associate Operations Analyst",
    "Associate Platform Engineer",
    "Associate Product Manager",
    "Associate Program Analyst",
    "Associate Project Manager",
    "Associate QA Engineer",
    "Associate Research Analyst",
    "Associate Security Analyst",
    "Associate Security Engineer",
    "Associate Site Reliability Engineer",
    "Associate Software Developer",
    "Associate Software Engineer",
    "Associate Solutions Architect",
    "Associate Solutions Engineer",
    "Associate Systems Administrator",
    "Associate Systems Engineer",
    "Associate Technical Support Engineer",
    "Associate Technical Writer",
    "Associate UI Designer",
    "Associate UX Designer",
    "Associate Web Developer",
    "Audio Engineer",
    "Auditor",
    "Automation Controls Engineer",
    "Automation Engineer",
    "Aviation Maintenance Technician",
    "AWS Cloud Engineer",
    "Azure Administrator",
    "Azure Engineer",
    "Back End Developer",
    "Banker",
    "Barista",
    "Benefits Specialist",
    "Biomedical Engineer",
    "Bookkeeper",
    "Brand Manager",
    "Budget Analyst",
    "Build Engineer",
    "Business Analyst",
    "Business Consultant",
    "Business Development Manager",
    "Business Development Representative",
    "Business Intelligence Analyst",
    "Business Intelligence Developer",
    "Business Operations Analyst",
    "Business Operations Manager",
    "Business Systems Analyst",
    "Buyer",
    "C# Developer",
    "C++ Developer",
    "CAD Designer",
    "CAD Technician",
    "Call Center Representative",
    "Channel Account Manager",
    "Chef",
    "Chemical Engineer",
    "Chief Information Officer",
    "Chief Information Security Officer",
    "Chief Technology Officer",
    "Civil Engineer",
    "Claims Adjuster",
    "Client Services Specialist",
    "Client Success Manager",
    "Clinical Research Associate",
    "Clinical Research Coordinator",
    "Cloud Administrator",
    "Cloud Architect",
    "Cloud Consultant",
    "Cloud Engineer",
    "Cloud Security Analyst",
    "Cloud Security Architect",
    "Cloud Security Engineer",
    "Cloud Support Associate",
    "Cloud Support Engineer",
    "Communications Specialist",
    "Community Manager",
    "Compliance Analyst",
    "Compliance Specialist",
    "Computer Support Specialist",
    "Computer Systems Analyst",
    "Construction Manager",
    "Construction Project Manager",
    "Content Designer",
    "Content Marketing Specialist",
    "Content Strategist",
    "Content Writer",
    "Contract Administrator",
    "Contract Specialist",
    "Controls Engineer",
    "Cook",
    "Copywriter",
    "Corporate Trainer",
    "Credit Analyst",
    "CRM Administrator",
    "CRM Developer",
    "Curriculum Developer",
    "Customer Service Representative",
    "Customer Success Engineer",
    "Customer Success Manager",
    "Customer Success Specialist",
    "Customer Support Representative",
    "Customer Support Specialist",
    "Cyber Defense Analyst",
    "Cybersecurity Analyst",
    "Cybersecurity Analyst I",
    "Cybersecurity Analyst II",
    "Cybersecurity Analyst III",
    "Data Analyst",
    "Data Architect",
    "Data Engineer",
    "Data Scientist",
    "Database Administrator",
    "Database Developer",
    "Delivery Driver",
    "Desktop Support Engineer",
    "Desktop Support Technician",
    "Developer Advocate",
    "Developer Relations Engineer",
    "DevOps Engineer",
    "Digital Forensics Analyst",
    "Digital Marketing Specialist",
    "Director of Cybersecurity",
    "Director of Engineering",
    "Director of Information Technology",
    "Director of Operations",
    "Director of Product Management",
    "Director of Software Engineering",
    "Dispatcher",
    "Documentation Specialist",
    "Drafter",
    "Driver",
    "E Commerce Manager",
    "E Commerce Specialist",
    "Education Program Coordinator",
    "Electrical Engineer",
    "Electrical Technician",
    "Email Marketing Specialist",
    "Embedded Software Engineer",
    "Emergency Management Coordinator",
    "Emergency Management Specialist",
    "End User Support Specialist",
    "Endpoint Administrator",
    "Engineering Manager",
    "Engineering Technician",
    "Enterprise Architect",
    "Entry Level Cybersecurity Analyst",
    "Entry Level Software Developer",
    "Entry Level Software Engineer",
    "Environmental Engineer",
    "ERP Analyst",
    "ERP Consultant",
    "Estimator",
    "ETL Developer",
    "Event Coordinator",
    "Event Manager",
    "Exchange Administrator",
    "Executive Assistant",
    "Facilities Manager",
    "Facilities Technician",
    "Field Engineer",
    "Field Service Technician",
    "Financial Advisor",
    "Financial Analyst",
    "Firmware Engineer",
    "Fleet Coordinator",
    "Fleet Manager",
    "Flight Attendant",
    "Front End Developer",
    "Full Stack Developer",
    "Game Designer",
    "Game Developer",
    "General Manager",
    "Geospatial Intelligence Analyst",
    "Google Cloud Engineer",
    "Government Affairs Specialist",
    "Graphic Designer",
    "GRC Analyst",
    "Growth Marketing Manager",
    "Hardware Engineer",
    "Health Information Technician",
    "Healthcare Administrator",
    "Healthcare Analyst",
    "Help Desk Technician",
    "HR Analyst",
    "HR Coordinator",
    "HR Manager",
    "Human Resources Generalist",
    "Human Resources Specialist",
    "IAM Analyst",
    "Identity and Access Management Engineer",
    "Implementation Consultant",
    "Implementation Specialist",
    "Incident Responder",
    "Incident Response Analyst",
    "Industrial Engineer",
    "Information Security Analyst",
    "Information Security Specialist",
    "Information Technology Manager",
    "Information Technology Specialist",
    "Information Technology Support Specialist",
    "Information Technology Technician",
    "Infrastructure Engineer",
    "Inside Sales Representative",
    "Instructional Designer",
    "Instructor",
    "Insurance Analyst",
    "Intelligence Analyst",
    "Interaction Designer",
    "Internal Auditor",
    "Intune Administrator",
    "Inventory Analyst",
    "Inventory Specialist",
    "Investigator",
    "Investment Analyst",
    "iOS Developer",
    "IT Analyst",
    "IT Consultant",
    "IT Coordinator",
    "IT Manager",
    "IT Operations Analyst",
    "IT Operations Specialist",
    "IT Project Manager",
    "IT Specialist",
    "IT Support Specialist",
    "IT Support Technician",
    "IT Technician",
    "Java Developer",
    "JavaScript Developer",
    "Junior Back End Developer",
    "Junior Business Analyst",
    "Junior Civil Engineer",
    "Junior Cloud Engineer",
    "Junior Cybersecurity Analyst",
    "Junior Data Analyst",
    "Junior Data Engineer",
    "Junior Data Scientist",
    "Junior DevOps Engineer",
    "Junior Electrical Engineer",
    "Junior Financial Analyst",
    "Junior Front End Developer",
    "Junior Full Stack Developer",
    "Junior Help Desk Technician",
    "Junior Industrial Engineer",
    "Junior IT Support Specialist",
    "Junior Machine Learning Engineer",
    "Junior Management Analyst",
    "Junior Marketing Analyst",
    "Junior Mechanical Engineer",
    "Junior Network Engineer",
    "Junior Operations Analyst",
    "Junior Platform Engineer",
    "Junior Product Manager",
    "Junior Program Analyst",
    "Junior Project Manager",
    "Junior QA Engineer",
    "Junior Research Analyst",
    "Junior Security Analyst",
    "Junior Security Engineer",
    "Junior Site Reliability Engineer",
    "Junior Software Developer",
    "Junior Software Engineer",
    "Junior Solutions Architect",
    "Junior Solutions Engineer",
    "Junior Systems Administrator",
    "Junior Systems Engineer",
    "Junior Technical Support Engineer",
    "Junior Technical Writer",
    "Junior UI Designer",
    "Junior UX Designer",
    "Junior Web Developer",
    "Key Account Manager",
    "Lab Assistant",
    "Laboratory Technician",
    "Lead Back End Developer",
    "Lead Business Analyst",
    "Lead Civil Engineer",
    "Lead Cloud Engineer",
    "Lead Cybersecurity Analyst",
    "Lead Data Analyst",
    "Lead Data Engineer",
    "Lead Data Scientist",
    "Lead DevOps Engineer",
    "Lead Electrical Engineer",
    "Lead Financial Analyst",
    "Lead Front End Developer",
    "Lead Full Stack Developer",
    "Lead Help Desk Technician",
    "Lead Industrial Engineer",
    "Lead IT Support Specialist",
    "Lead Machine Learning Engineer",
    "Lead Management Analyst",
    "Lead Marketing Analyst",
    "Lead Mechanical Engineer",
    "Lead Network Engineer",
    "Lead Operations Analyst",
    "Lead Platform Engineer",
    "Lead Product Manager",
    "Lead Program Analyst",
    "Lead Project Manager",
    "Lead QA Engineer",
    "Lead Research Analyst",
    "Lead Security Analyst",
    "Lead Security Engineer",
    "Lead Site Reliability Engineer",
    "Lead Software Developer",
    "Lead Software Engineer",
    "Lead Solutions Architect",
    "Lead Solutions Engineer",
    "Lead Systems Administrator",
    "Lead Systems Engineer",
    "Lead Technical Support Engineer",
    "Lead Technical Writer",
    "Lead UI Designer",
    "Lead UX Designer",
    "Lead Web Developer",
    "Learning and Development Specialist",
    "Legal Assistant",
    "Level 1 Help Desk Technician",
    "Level 2 Help Desk Technician",
    "Level 3 Help Desk Technician",
    "Level Designer",
    "Licensed Practical Nurse",
    "Linux Administrator",
    "Loan Officer",
    "Logistics Analyst",
    "Logistics Coordinator",
    "Logistics Manager",
    "Machine Learning Engineer",
    "Maintenance Engineer",
    "Maintenance Technician",
    "Malware Analyst",
    "Management Analyst",
    "Management Consultant",
    "Manual Tester",
    "Manufacturing Engineer",
    "Market Research Analyst",
    "Marketing Analyst",
    "Marketing Coordinator",
    "Marketing Manager",
    "Marketing Specialist",
    "Mechanical Engineer",
    "Media Specialist",
    "Medical Assistant",
    "Medical Billing Specialist",
    "Medical Coder",
    "Member Services Representative",
    "Merchandiser",
    "Microsoft 365 Administrator",
    "MLOps Engineer",
    "Mobile Developer",
    "Mortgage Loan Officer",
    "Motion Graphics Designer",
    "Network Administrator",
    "Network Engineer",
    "Network Operations Specialist",
    "Network Security Engineer",
    "Network Technician",
    "NOC Analyst",
    "NOC Technician",
    "Nursing Assistant",
    "Occupational Therapist",
    "Office Manager",
    "Operations Analyst",
    "Operations Coordinator",
    "Operations Manager",
    "Operations Research Analyst",
    "Operations Specialist",
    "Oracle Consultant",
    "Outside Sales Representative",
    "Package Handler",
    "Paralegal",
    "Partner Manager",
    "Patient Care Technician",
    "Payroll Specialist",
    "Penetration Tester",
    "People Operations Specialist",
    "Performance Test Engineer",
    "Personal Banker",
    "Pharmacy Technician",
    "Photographer",
    "PHP Developer",
    "Physical Therapist",
    "Pilot",
    "Platform Engineer",
    "Police Officer",
    "Policy Analyst",
    "Practice Manager",
    "Pricing Analyst",
    "Principal Back End Developer",
    "Principal Business Analyst",
    "Principal Civil Engineer",
    "Principal Cloud Engineer",
    "Principal Cybersecurity Analyst",
    "Principal Data Analyst",
    "Principal Data Engineer",
    "Principal Data Scientist",
    "Principal DevOps Engineer",
    "Principal Electrical Engineer",
    "Principal Financial Analyst",
    "Principal Front End Developer",
    "Principal Full Stack Developer",
    "Principal Help Desk Technician",
    "Principal Industrial Engineer",
    "Principal IT Support Specialist",
    "Principal Machine Learning Engineer",
    "Principal Management Analyst",
    "Principal Marketing Analyst",
    "Principal Mechanical Engineer",
    "Principal Network Engineer",
    "Principal Operations Analyst",
    "Principal Platform Engineer",
    "Principal Product Manager",
    "Principal Program Analyst",
    "Principal Project Manager",
    "Principal QA Engineer",
    "Principal Research Analyst",
    "Principal Security Analyst",
    "Principal Security Engineer",
    "Principal Site Reliability Engineer",
    "Principal Software Developer",
    "Principal Software Engineer",
    "Principal Solutions Architect",
    "Principal Solutions Engineer",
    "Principal Systems Administrator",
    "Principal Systems Engineer",
    "Principal Technical Support Engineer",
    "Principal Technical Writer",
    "Principal UI Designer",
    "Principal UX Designer",
    "Principal Web Developer",
    "Process Engineer",
    "Procurement Analyst",
    "Procurement Specialist",
    "Producer",
    "Product Designer",
    "Product Manager",
    "Product Marketing Manager",
    "Product Owner",
    "Production Assistant",
    "Professor",
    "Program Analyst",
    "Program Coordinator",
    "Program Manager",
    "Project Analyst",
    "Project Coordinator",
    "Project Engineer",
    "Project Manager",
    "Public Affairs Specialist",
    "Public Relations Specialist",
    "Purchasing Agent",
    "Python Developer",
    "QA Analyst",
    "QA Engineer",
    "Quality Assurance Engineer",
    "Quality Engineer",
    "Radiologic Technologist",
    "Ramp Agent",
    "React Developer",
    "Receptionist",
    "Recruiter",
    "Regional Sales Manager",
    "Registered Nurse",
    "Relationship Banker",
    "Release Engineer",
    "Requirements Analyst",
    "Research Analyst",
    "Research Assistant",
    "Research Associate",
    "Research Scientist",
    "Respiratory Therapist",
    "Restaurant Manager",
    "Retail Associate",
    "Revenue Analyst",
    "Risk Analyst",
    "Robotics Engineer",
    "Route Driver",
    "Ruby Developer",
    "Sales Associate",
    "Sales Development Representative",
    "Sales Engineer",
    "Sales Manager",
    "Sales Representative",
    "Salesforce Administrator",
    "Salesforce Business Analyst",
    "Salesforce Consultant",
    "Salesforce Developer",
    "Salesforce Solution Architect",
    "Salesforce Solution Engineer",
    "SAP Analyst",
    "SAP Consultant",
    "Scrum Master",
    "Security Analyst",
    "Security Architect",
    "Security Consultant",
    "Security Control Assessor",
    "Security Engineer",
    "Security Manager",
    "Security Officer",
    "Security Operations Analyst",
    "Security Operations Center Analyst",
    "Security Specialist",
    "SEM Specialist",
    "Senior Back End Developer",
    "Senior Business Analyst",
    "Senior Civil Engineer",
    "Senior Cloud Engineer",
    "Senior Cybersecurity Analyst",
    "Senior Data Analyst",
    "Senior Data Engineer",
    "Senior Data Scientist",
    "Senior DevOps Engineer",
    "Senior Electrical Engineer",
    "Senior Financial Analyst",
    "Senior Front End Developer",
    "Senior Full Stack Developer",
    "Senior Help Desk Technician",
    "Senior Industrial Engineer",
    "Senior IT Support Specialist",
    "Senior Machine Learning Engineer",
    "Senior Management Analyst",
    "Senior Marketing Analyst",
    "Senior Mechanical Engineer",
    "Senior Network Engineer",
    "Senior Operations Analyst",
    "Senior Platform Engineer",
    "Senior Product Manager",
    "Senior Program Analyst",
    "Senior Project Manager",
    "Senior QA Engineer",
    "Senior Research Analyst",
    "Senior Security Analyst",
    "Senior Security Engineer",
    "Senior Site Reliability Engineer",
    "Senior Software Developer",
    "Senior Software Engineer",
    "Senior Solutions Architect",
    "Senior Solutions Engineer",
    "Senior Systems Administrator",
    "Senior Systems Engineer",
    "Senior Technical Support Engineer",
    "Senior Technical Writer",
    "Senior UI Designer",
    "Senior UX Designer",
    "Senior Web Developer",
    "SEO Specialist",
    "Server",
    "Service Desk Analyst",
    "ServiceNow Administrator",
    "ServiceNow Consultant",
    "ServiceNow Developer",
    "SharePoint Administrator",
    "Shift Manager",
    "Shopify Developer",
    "Site Reliability Engineer",
    "SOC Analyst",
    "Social Media Manager",
    "Social Media Specialist",
    "Software Architect",
    "Software Developer",
    "Software Engineer",
    "Software Engineer I",
    "Software Engineer II",
    "Software Engineer III",
    "Software Engineering Manager",
    "Software Test Engineer",
    "Solutions Architect",
    "Solutions Engineer",
    "Sound Designer",
    "SQL Developer",
    "Staff Accountant",
    "Store Manager",
    "Student Services Coordinator",
    "Supply Chain Analyst",
    "Supply Chain Manager",
    "Supply Chain Specialist",
    "Surgical Technologist",
    "Systems Administrator",
    "Systems Analyst",
    "Systems Engineer",
    "Systems Engineer I",
    "Systems Engineer II",
    "Systems Engineer III",
    "Systems Support Specialist",
    "Talent Acquisition Specialist",
    "Tax Accountant",
    "Tax Analyst",
    "Teacher",
    "Teaching Assistant",
    "Technical Account Manager",
    "Technical Architect",
    "Technical Business Analyst",
    "Technical Consultant",
    "Technical Product Manager",
    "Technical Program Manager",
    "Technical Project Manager",
    "Technical Recruiter",
    "Technical Support Engineer",
    "Technical Support Specialist",
    "Technical Writer",
    "Technology Consultant",
    "Telecommunications Technician",
    "Test Automation Engineer",
    "Threat Hunter",
    "Threat Intelligence Analyst",
    "Tier 1 Help Desk Technician",
    "Tier 2 Help Desk Technician",
    "Tier 3 Help Desk Technician",
    "Training Coordinator",
    "Training Specialist",
    "Transportation Analyst",
    "Truck Driver",
    "UI Designer",
    "UI Developer",
    "UI/UX Designer",
    "Underwriter",
    "Unity Developer",
    "Unreal Engine Developer",
    "UX Designer",
    "UX Researcher",
    "Video Editor",
    "Videographer",
    "Visual Designer",
    "VP of Engineering",
    "VP of Information Technology",
    "Vulnerability Analyst",
    "Warehouse Associate",
    "Warehouse Manager",
    "Warehouse Supervisor",
    "Web Designer",
    "Web Developer",
    "Windows Administrator",
    "WordPress Developer",
];
